### ISSUE TITLE
github pages sample app doesn't work when directly opening a deep URL

### ISSUE THREAD

**Issue by saithis** [prosoft-edv/components#46]
directly opening for example https://prosoft-edv.github.io/components/components/table doesn't work, as github tries to open a components/table/index.html, which doesn't exist.

**Comment by saithis** [comment]
could be fixed when duplicating the root index.html as 404.html

or we use https://www.npmjs.com/package/angular-cli-ghpages for deployment

**Comment by 6rayWolf** [comment]
I think we should fix this when we switch to storybook because the actual deployment will change then anyways.

#53
